server:
  port: 8085

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-map

# 自定义的 key：value
amap:
  key: 9fde526a626b02bf16f473049faf2f07